# https://doc.rust-lang.org/cargo/reference/config.html

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.dev.package.backtrace]
opt-level = 3

[env]
LIBSQLITE3_FLAGS = { value = "-DSQLITE_ENABLE_MATH_FUNCTIONS", force = true }
